{
 "title": "RepeaterDashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service/Backend Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{RepeaterSide=\"Backend/Service\"} |= `stop` | line_format `Stopped`"
    },
    {
     "expr": "{RepeaterSide=\"Backend/Service\"} |= `start` | line_format `Running`"
    }
   ]
  },
  {
   "title": "Packets Handled per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "rate(TotalPacketsHandled_total{job=\"unknown_service:UDP_Repeater_Service\"}[$__rate_interval]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Project requirements specified 30ms or less",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(packetHandling_sum[$__rate_interval]) / rate(packetHandling_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{RepeaterSide=\"Backend/Service\"}"
    },
    {
     "expr": "{RepeaterSide=\"Frontend/Interface\"} |= ``"
    }
   ]
  },
  {
   "title": "Service/Backend Errors in Time Frame",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({RepeaterSide=\"Backend/Service\"} |= `Error` [$__auto]))"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backendMemory{job=\"unknown_service:UDP_Repeater_Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frontendMemory", "legendFormat": "__auto" }
   ]
  }
 ]
}